[versions]
java = "17"
spring-boot = "3.1.5"
spring-dependencies-management = "1.1.4"

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependencies-management = { id = "io.spring.dependency-management", version.ref = "spring-dependencies-management" }

