[versions]
gorylenko-git-properties = "2.5.4"
mockito-kotlin = "6.1.0"
spotless = "7.2.1"
spring-boot = "3.5.8"
spring-cloud = "2025.0.0"
spring-dependency-management = "1.1.7"

[plugins]
gorylenko-git-properties = { id = "com.gorylenko.gradle-git-properties", version.ref = "gorylenko-git-properties" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
